# Generated by Django 4.0.5 on 2022-07-05 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_marca_producto_remove_remedio_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='marca',
        ),
        migrations.DeleteModel(
            name='Marca',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
